### ISSUE TITLE
flv 播放出现 Error: 31,-5 错误 无法进行重连（Buffer过程中出现EOF!）

### ISSUE THREAD

**Issue by jiajialaixi** [RTE-Dev/REDPlayer#10]
[日志.txt](https://github.com/RTE-Dev/REDPlayer/files/14532172/default.txt)
流：https://sdcvr.sdvideo.cn:4443/flv/live/34020000001320000052_34020000001320000052_0200000052.flv

**Comment by Tonghuaaaa** [comment]
This video stream also have problems when played on ijkplayer, VLC, and ffplay. Please confirm that it is not a source stream issue by using the above-mentioned players before submitting an issue. Thx
