### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: library "libijkffmpeg.so" not found

### ISSUE THREAD

**Issue by jiajialaixi** [RTE-Dev/REDPlayer#18]
通过 https://github.com/RTE-Dev/FFmpeg/tree/redplayer-n4.3.1 编译libffmpeg.so 替换extra目录下的文件

加载redsource.so文件出现dlopen failed: library "libijkffmpeg.so" not found错误

**Comment by jiajialaixi** [comment]
<img width="1013" alt="image" src="https://github.com/RTE-Dev/REDPlayer/assets/20548416/361e164c-2c81-48ad-bf3c-b1ab86e9da23">

**Comment by Tonghuaaaa** [comment]
Please click on 'Build -> Clean Project' in Android Studio and try again. If there are still issues, please run 'git clean -xdf' in the project root directory and try again.

**Comment by jiajialaixi** [comment]
这个解决方案无效
