### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: library "libijkffmpeg.so" not found

### ISSUE THREAD

**Issue by jiajialaixi** [RTE-Dev/REDPlayer#19]
#18  这个解决方案无效。

redsource.so,redrender.so,reddecoder.so,redplayer.so都引用了libijkffmpeg.so 但是找不到在哪里引用的

**Comment by Tonghuaaaa** [comment]
<img width="829" alt="redsource" src="https://github.com/RTE-Dev/REDPlayer/assets/157354930/09a3a153-3a22-4766-9d52-8cd9b583e970">
You can use the 'readelf -d libredsource.so' command to view the dependencies of the so file. The image above shows the dependencies of the latest version of libredsource.so. Please make sure that the so files in your local repository is up to date. If there are still issues, please push your repository to GitHub and we will debug based on your repository.

**Comment by jiajialaixi** [comment]
arm64-v8a 不存在引用libijkffmpeg.so。但是 armeabi-v7a目录下的.so文件存在

**Comment by jiajialaixi** [comment]
<img width="1024" alt="image" src="https://github.com/RTE-Dev/REDPlayer/assets/20548416/3898da32-b7c5-4e94-b1d1-07d2126dc4e5">
<img width="997" alt="image" src="https://github.com/RTE-Dev/REDPlayer/assets/20548416/c71763a4-bf7b-42bb-90fc-48eb13c457de">

**Comment by Tonghuaaaa** [comment]
Please download the latest version and try again.
