### ISSUE TITLE
倍速是否可以支持6倍速或者8倍速

### ISSUE THREAD

**Issue by jiajialaixi** [RTE-Dev/REDPlayer#26]
我看代码是没有限制倍速的但是设置6倍速或者8倍速不生效

**Comment by Tonghuaaaa** [comment]
The setSpeed method is available for Android, whereas the setPlaybackRate method can be used on iOS. Please confirm whether the decoding performance of the device supports high-speed playback.

**Comment by jiajialaixi** [comment]
当设备不支持高速播放的情况的话 设置8倍速可以动态丢帧进行处理嘛

**Comment by jiajialaixi** [comment]
然后可以新增一个是否只解码视频帧不解码音频帧配置项

**Comment by hongdaLL** [comment]
This requires developers to experiment based on their own needs.
