### ISSUE TITLE
我正在实现视频录制的功能，我从什么地方的代码获取到音视频的AvPacket 我需要写入的文件中能否给予一些帮助

### ISSUE THREAD

**Issue by jiajialaixi** [RTE-Dev/REDPlayer#27]

**Comment by Tonghuaaaa** [comment]
We use the readPacket method in the [https://github.com/RTE-Dev/REDPlayer/blob/main/source/redplayercore/redplayer/RedCore/module/sourcer/RedSourceController.cpp](url) to obtain AVPacket.

**Comment by jiajialaixi** [comment]
你好👋我看了这部分的代码貌似是缓冲中的AVPacket我在那里可以获取到正在播放中的AVPacket

**Comment by jiajialaixi** [comment]
目前就差最后一步要是可以知道正在播放的中AVPacket 我这个功能就可以实现，在[https://github.com/RTE-Dev/REDPlayer/blob/main/source/redplayercore/redplayer/RedCore/module/sourcer/RedSourceController.cpp](https://github.com/RTE-Dev/REDPlayer/issues/url)中 readPacket 地方只要在视频缓冲的过程中才能获取到AVPacket正在播放的就无法拿到pkt

**Comment by jiajialaixi** [comment]
是否有其他地方可以获取到🙏正在播放的AVPacket

**Comment by Tonghuaaaa** [comment]
We use the DecoderTransmit method in the [to](https://github.com/RTE-Dev/REDPlayer/blob/main/source/redplayercore/redplayer/RedCore/module/processer/VideoProcesser.cpp) to send AVPacket to decoder.

**Comment by jiajialaixi** [comment]
我发现当播放MP4文件时[VideoProcesser.cpp](https://github.com/RTE-Dev/REDPlayer/blob/main/source/redplayercore/redplayer/RedCore/module/processer/VideoProcesser.cpp)中的DecoderTransmit  中的 AVPacket 使用avcodec_receive_packet 发现它返回AVERROR(EAGAIN) 这看起来并不是一个有效的AVPacket数据

**Comment by Tonghuaaaa** [comment]
avcodec_receive_packet  is used to read encoded data from the encoder rather than decoder
