### ISSUE TITLE
CicadaPlayer 对比

### ISSUE THREAD

**Issue by xfirefly** [RTE-Dev/REDPlayer#29]
上个项目用的 https://github.com/alibaba/CicadaPlayer . 也是基于 ffmpeg , 新项目想试试 REDPlayer. 

请问相比 CicadaPlayer  , REDPlayer 有哪些优势?  看代码有so 和 aar, 是有部分代码还没有开源吗?

**Comment by yifengch** [comment]
The code will be open-sourced gradually.
Redplayer supports a variety of features such as preloading, and it has excellent performance.
