### ISSUE TITLE
FORTIFY: strcpy: prevented write past end of 288-byte buffer

### ISSUE THREAD

**Issue by jiajialaixi** [RTE-Dev/REDPlayer#30]
我在ffmpeg中添加了[metartc](https://github.com/metartc/ffmpeg-webrtc) 集成到redplayer中发现播放webrtc流崩溃 ,查看这个strcpy函数发现在libred...so文件中
<img width="696" alt="image" src="https://github.com/RTE-Dev/REDPlayer/assets/20548416/9ca6b4ca-1806-46ef-931c-3346ee849b78">

下面是我编译的libffmpeg.so文件
[android.zip](https://github.com/RTE-Dev/REDPlayer/files/15034114/android.zip)

**Comment by yifengch** [comment]
strcpy is a standard library function, not a private function of Redplayer. Please check your code against the crash stack.
