### ISSUE TITLE
hls流 seek出现视频卡死问题

### ISSUE THREAD

**Issue by jiajialaixi** [RTE-Dev/REDPlayer#35]
https://cloud.lnton.com/drecords/cf419def39870454721ffc6b14cfe38c/api/record/hls/vod/index.m3u8?channel=0&start_time=1715356800000&end_time=1715443199999
当前hls流有时间有效期 此hls流时长大概在12个小时左右，设置seek时视频会出现卡死现象

**Comment by yifengch** [comment]
The stream you provided cannot be played. You may want to check the issue with ffmpeg yourself. If the problem persists, feel free to open a new issue and attach the log.
