### ISSUE TITLE
onSeekComplete 返回seek完成时间比实际时间短，基本是调了seek，就返回，而实际现象seek时间更久

### ISSUE THREAD

**Issue by Cathy1994-lj** [RTE-Dev/REDPlayer#36]
@Override
         public void onSeekComplete(com.xingin.openredplayercore.core.api.IMediaPlayer mp) {
             RedPlayerMediaPlayer self = mWeakMediaPlayer.get();

             if (self == null)
                 return;
             self.infoCollector.onSeekComplete();
             notifyOnSeekComplete();
         }
这是我获取seek完成的方法

**Comment by yifengch** [comment]
MEDIA_SEEK_COMPLETE indicates that the seek call has been executed. The default setting is accurate seek.If you need to know when the accurate seek is completed, you can use MEDIA_INFO_MEDIA_ACCURATE_SEEK_COMPLETE to judge.
