### ISSUE TITLE
播放hevc直播流黑屏，是不支持直播吗

### ISSUE THREAD

**Issue by Cathy1994-lj** [RTE-Dev/REDPlayer#37]
播放直播流黑屏，问题时间点15:33
[red.zip](https://github.com/RTE-Dev/REDPlayer/files/15282272/red.zip)

**Comment by jiajialaixi** [comment]
需要自己编版ffmpeg 现在这个框架目前用的是4.3版本 目前的ffmpeg新版本是支持flv256  目前使用的需要添加补丁自己编译

**Comment by yifengch** [comment]
The current version of ffmpeg does not support  HEVC encoded Flv format.You can update ffmpeg to add this support.
