### ISSUE TITLE
ffmpeg不兼容6.1版本

### ISSUE THREAD

**Issue by jiajialaixi** [RTE-Dev/REDPlayer#39]
我正在尝试使用此播放器播放rtmp与webrtc文件

1、无法使用6.0版本中的mediacodec特性     
2、无法使用flv、rtmp中HEVC、AV1 编解码器
3、根据libdatachannel添加ffmpeg 实现whep 

我根据参考资料1发现好多api不支持，通过构建ffmpeg6.1版本后redplay不支持
问题1可以先不解决
问题2目前可以通过patch的方式支持hevc 
问题3是完全不支持

参考资料
1、[这个pr可以在ffmeg中实现whep与whip](https://github.com/nativewaves/FFmpeg/pull/1) 
2、[srs组织实现的ffmpeg-whip](https://github.com/ossrs/ffmpeg-webrtc) 
3、[obs 实现whep跟whip 原理也是通过libdatachannel进行交换rtsp ffmpeg进行解码](https://github.com/obsproject/obs-studio/pull/10353)

**Comment by yifengch** [comment]
We will soon open-source all modules. Regarding the FFmpeg-related functionalities, you are free to modify them. Stay tuned.
