### ISSUE TITLE
hls 片段出现404后一直重连无法进行播放，也无法进入到error

### ISSUE THREAD

**Issue by jiajialaixi** [RTE-Dev/REDPlayer#9]
[日志.txt](https://github.com/RTE-Dev/REDPlayer/files/14532151/default.txt)

流：https://sdcvr.sdvideo.cn:4443/hls/34020000001320000052_34020000001320000052_0200000052/playlist.m3u8

**Comment by yifengch** [comment]
[hls @ 0x75bb21d200] Skip ('#EXT-X-DISCONTINUITY') The current version is using https://github.com/RTE-Dev/FFmpeg, which does not support DISCONTINUITY. You can modify it in https://github.com/RTE-Dev/FFmpeg and replace it, or wait for future updates.
